export const GET_COUNTRIES = "GET_COUNTRIES";
export const POST_ACTIVITY = "POST_ACTIVITY";
export const PAGINATE="PAGINATE";
export const ORDER="ORDER";
export const POPULATION="POPULATION";
export const BYCONTINENT="BYCONTINENT";